version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: lesson_11_mysql
    ports:
      - '3306:3306'
    env_file:
      - ../docker/mysql/aw_mysql.env
    volumes:
      - /etc/hosts:/etc/hosts
      - ../docker/mysql/db_lesson_11:/var/lib/mysql
      - ../docker/logs:/var/log
      - ../docker/mysql/backup/AdventureWorks/AdventureWorks.sql:/docker-entrypoint-initdb.d/AdventureWorks.sql